### PR TITLE
Experiments with wrapping `git` CLI command with `CliWrap`

### PR DESCRIPTION
**Pull request by mscottford**
We've had some challenges with libgit2sharp. This experiment is trying to evaluate the feasibility of breaking our dependency with that package and instead, just using the `git` CLI to get the information that we need.

### CODE REVIEW

**Comment by mrbiggred** [comment]
@mscottford if I understand correctly removing the libgit2sharp library will require any consumers of this NuGet package to have Git installed.  Is that extra step, requiring Git to be installed in a path the NuGet package can find, easier then the trouble we are having with libgit2sharp?

What are the issues we are having with libgit2sharp?

**Comment by mscottford** [comment]
> @mscottford if I understand correctly removing the libgit2sharp library will require any consumers of this NuGet package to have Git installed. Is that extra step, requiring Git to be installed in a path the NuGet package can find, easier then the trouble we are having with libgit2sharp?

Yes, the `git` executable would need to be accessible via `PATH`. We could also support reading an environment variable to point to the location of the git executable if it's not found in the path. We could throw a friendly exception that details that as a requirement. We would probably also want to do some experiments to determine which versions of `git` we could support. For that we could run a git specific integration test in a variety of git version in CI. That could be accomplished using the build matrix support in GitHub Actions. I found a good blog post that details how to those work. https://ncorti.com/blog/howto-github-actions-build-matrix

> What are the issues we are having with libgit2sharp?

Good question. 

First up, support for this package is waning and there is a need for additional maintainers (see: https://github.com/libgit2/libgit2sharp/issues/1834). I don't feel like we have the resources that would be needed to get involved, and behavior that we need from the library is rather limited.

We've also logged some past issues with this library in the past. 
* Take a peek at #205 to see an issue with files with really long paths, which has been fixed in the upstream libgit2 library, but hasn't been fixed in the C# wrapper, yet.
* We also ran into some problems getting the history that we had to figure out some work arounds for. That's documented in #79.

Next up are some comments that I've seen while reading through the project's issues.
* Issue https://github.com/libgit2/libgit2sharp/issues/1843 which details performance challenges when getting the history for a file.
* Issue https://github.com/libgit2/libgit2sharp/issues/1837 which detalis some potential memory leaks which could cause us challenges
* A note that the Visual Studio team has started wrapping the `git` binary actually gave me the idea to explore this in detail (see: https://github.com/libgit2/libgit2sharp/issues/1833#issuecomment-721264984)
* Also since we really only need the history for a few files in a project, we could experiment with git spare checkout, but that's something that's not currently supported by libgit2sharp (see: https://github.com/libgit2/libgit2sharp/issues/1845)

**Comment by mscottford** [comment]
This train-wreck of a monster pull-request is ready for review. At the moment, the class that wraps the `git` cli command is included, but it is not being used by the `GitFileHistory` class. So, if this were merged in today, then it would essentially just implement the switch to using `DateTimeOffset` everywhere.

Since this is such a mess, one option is to break it up into smaller pull requests that can be evaluated easier. Or we can just move forward and accept the messiness in the commit history.

**Comment by mscottford** [comment]
This work is being abandoned in favor of the approach taken in the Freshli-CLI project.

**Pull request closed without merging**
