### PR TITLE
Fix project build and test issues [closes #504]

### LINKED ISSUE #504: Project won't build
Since commit 84f5ef16d235949b31aa8615702d9a1a763f3d0e, the project build fails with the following error:

```
/freshli/Corgibytes.Freshli.Lib.Test/Initializer.cs(19,26): error CS1061: 'SerializationSettings' does not contain a definition for 'MemberConverter' and no accessible extension method 'MemberConverter' accepting a first argument of type 'SerializationSettings' could be found (are you missing a using directive or an assembly reference?)
[/freshli/Corgibytes.Freshli.Lib.Test/Corgibytes.Freshli.Lib.Test.csproj]
```

That commit only updated Verify.DiffPlex from 1.1.0 to 1.2.0, so let's see what changed in that package...

### PR DESCRIPTION
**Pull request by marnen**
See #504.

### CODE REVIEW

**Comment by marnen** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by marnen** [comment]
recheck

**Comment by marnen** [comment]
BTW, note that both the issues fixed in this pull request come from Dependabot changes being automerged even though the builds failed. How can we prevent this in future?

**Comment by marnen** [comment]
Ah, it appears that our [current Dependabot workflow](https://github.com/corgibytes/freshli-lib/blob/5d5a7d45647a602db23931a07d1ab220a6a7225b/.github/dependabot.yml) approves all patch _and minor_ updates, regardless of the build status. We need to fix that so Dependabot doesn't break the build.

**Comment by mscottford** [comment]
This is superseded by #577.

**Pull request closed without merging**
