### PR TITLE
(#259) - Rename namespace from Freshli.* to Corgibytes.Freshli.Lib.* 

### PR DESCRIPTION
**Pull request by mfcorgi**
Rename namespace from Freshli.* to Corgibytes.Freshli.Lib.* and from Freshli.Test.* to Corgibytes.Freshli.Lib.Test.*

### CODE REVIEW

**Comment by mfcorgi** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mfcorgi** [comment]
recheck

**Comment by mrbiggred** [comment]
@mfcorgi can you please fix the failing build checks and merge conflicts before asking for a PR review?  The failing CLA assistant is easily fixed by following the instructions here:

https://github.com/corgibytes/freshli-lib/pull/276#issuecomment-796415445

My guess is the .NET Core build is failing because of files being renamed:

https://github.com/corgibytes/freshli-lib/pull/276/checks?check_run_id=2083053518

I'm going to switch this PR to draft status until the build issues are fixed.

**Comment by mfcorgi** [comment]
> @mfcorgi can you please fix the failing build checks and merge conflicts before asking for a PR review? The failing CLA assistant is easily fixed by following the instructions here:
> 
> [#276 (comment)](https://github.com/corgibytes/freshli-lib/pull/276#issuecomment-796415445)
> 
> My guess is the .NET Core build is failing because of files being renamed:
> 
> https://github.com/corgibytes/freshli-lib/pull/276/checks?check_run_id=2083053518
> 
> I'm going to switch this PR to draft status until the build issues are fixed.

I do don understand where do I have to post that comment @mrbiggred . I already did that and nothing happened. You can see my comments.

**Comment by mfcorgi** [comment]
> > @mfcorgi can you please fix the failing build checks and merge conflicts before asking for a PR review? The failing CLA assistant is easily fixed by following the instructions here:
> > [#276 (comment)](https://github.com/corgibytes/freshli-lib/pull/276#issuecomment-796415445)
> > My guess is the .NET Core build is failing because of files being renamed:
> > https://github.com/corgibytes/freshli-lib/pull/276/checks?check_run_id=2083053518
> > I'm going to switch this PR to draft status until the build issues are fixed.
> 
> I do don understand where do I have to post that comment @mrbiggred . I already did that and nothing happened. You can see my comments.

I am going to rebase and fix the conflicts. Looks like some push we did last week got in conflict with this PR.

**Comment by mfcorgi** [comment]
> @mfcorgi can you please fix the failing build checks and merge conflicts before asking for a PR review? The failing CLA assistant is easily fixed by following the instructions here:
> 
> [#276 (comment)](https://github.com/corgibytes/freshli-lib/pull/276#issuecomment-796415445)
> 
> My guess is the .NET Core build is failing because of files being renamed:
> 
> https://github.com/corgibytes/freshli-lib/pull/276/checks?check_run_id=2083053518
> 
> I'm going to switch this PR to draft status until the build issues are fixed.

Yes, it is because of that but it does not let me push the github workflow file. because I do not have "workflow" permissions. I have to figure out how to configure that in Visual Studio.

**Comment by mrbiggred** [comment]
@mfcorgi I think the CLA signing is failing because the repository was renamed from `Freshli` to `Freshli-lib`.  To fix the workflow error:

```
! [remote rejected] freshli-259 -> freshli-259 (refusing to allow an OAuth App to create or update workflow `.github/workflows/dotnet-core.yml` without `workflow` scope)
```

I think you need to re-authenticate your Git client with GitHub.  For example, I use GitKraken and to fix I would need to go to:

https://github.com/settings/applications

revoke GitKraken access then re-enable GitKraken access and it should work.  What Git client are you using?  Check out the following for some more help:

https://github.com/github/VisualStudio/issues/2455

**Review by dfar-io — APPROVED** [review]
:+1: there's a lot of files here but since checks are all passing it should be good to go.

**Pull request merged**
