### PR TITLE
Moves CodeClimate links to a publicly accessible open-source account

### PR DESCRIPTION
**Pull request by mscottford**
The secret used by GitHub Actions to send code coverage has also been updated to point to the new location.

### CODE REVIEW

**Comment by mscottford** [comment]
Hmm... looks like this is actually caused by the checks _not_ running on the changelog update commit... as can be seen in the [documentation for the action](https://github.com/stefanzweifel/git-auto-commit-action#commits-of-this-action-do-not-trigger-new-workflow-runs) that's being used to create the commit.

> The resulting commit **will not trigger** another GitHub Actions Workflow run.

**Comment by mscottford** [comment]
Once #287 is merged into this branch, then all of the checks should pass as expected.

**Comment by mrbiggred** [comment]
@mscottford does this fix #253?

**Review by mrbiggred — APPROVED** [review]
Links on the ReadMe work and I can see the new public Freshli Lib repo with test coverage.  Thanks @mscottford.

image

P.S. - Ignore the Release Notes check failing for this PR.  @mairadanielaferrari has fix in #290.

**Pull request merged**
